---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - golang
    - nodejs

- hosts: all
  become: yes
  become_user: vagrant
  vars_files:
    - vars/all.yml
  roles:
    - app